version: '3.4'

services:
  webapi:
    image: webapi
    environment:
      - ASPNETCORE_URLS=http://+:80
    build:
      context: .
      dockerfile: TimeTracker/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - sqlserver
    
  sqlserver:
    restart: unless-stopped
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    environment:
      - SA_PASSWORD=P@ssword123
      - ACCEPT_EULA=Y
    volumes:
      - "./data-mssql:/var/opt/mssql/data"
    ports:
      - "5050:1433"
